# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: a8f8cbbb24ebcb264e2256b51528f00b407976ff8a2b942982766d9d30ae2b304fb855b84c5c428d0131f73c6466c0ac610896de8e9b3545ce4aa1ee5d329fb5

test:
  secret_key_base: caffdeb60fe0be16c5639acf025659784f6731116b9234fe38d392c310c2b4ff2a533e809f253ad6b9861abecd8c663de37949a16ac1b12d25f73a9696be2dc7

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
